export const ADD_FILM = "ADD_FILM";
export const INIT_FILM = "INIT_FILM";
export const INIT_FILM_SUCCES = "INIT_FILM_SUCCES";
export const INIT_FILM_FAILED = "INIT_FILM_FAILED";
export const INIT_GENRES = "INIT_GENRES";
export const SET_GENRES = "SET_GENRES";

export const INIT_FAV_FILMS_SUCCESS = "INIT_FAV_FILMS_SUCCESS";
export const INIT_FAV_FILMS_FAILED = "INIT_FAV_FILMS_FAILED";
export const INIT_WATCHLIST_SUCCESS = "INIT_WATCHLIST_SUCCESS";
export const INIT_WATCHLIST_FAILED = "INIT_WATCHLIST_FAILED";
export const ADD_FAV_FILM_SUCCESS = "ADD_FAV_FILM_SUCCESS";
export const ADD_TO_WATCHLIST_SUCCES = "ADD_TO_WATCHLIST_SUCCES";
