export const ADD_FILM = "ADD_FILM";
export const INIT_FILM = "INIT_FILM";
export const INIT_POPFILMS_SUCCESS = "INIT_POPFILMS_SUCCESS";
export const INIT_FILM_SUCCES = "INIT_FILM_SUCCES";
export const INIT_FILM_FAILED = "INIT_FILM_FAILED";
export const INIT_GENRES = "INIT_GENRES";
export const SET_GENRES = "SET_GENRES";

export const INIT_FILMS_OPTIONS = "INIT_FILMS_OPTION";
export const INIT_FILMS_OPTIONS_SUCCESS = "INIT_FILMS_OPTION_SUCCESS";
export const ADD_FAV_FILM_SUCCESS = "ADD_FAV_FILM_SUCCESS";
export const ADD_TO_WATCHLIST_SUCCESS = "ADD_TO_WATCHLIST_SUCCESS";
export const ADD_RATING_SUCCESS = "ADD_RATING_SUCCESS";
export const GET_FILM_SUCCESS = "GET_FILM_SUCCESS";

export const REMOVE_FILM_FROM_FAV_SUCCESS = "REMOVE_FILM_FROM_FAV_SUCCESS";
export const REMOVE_FILM_FROM_FAV_WATCHLIST = "REMOVE_FILM_FROM_FAV_WATCHLIST";
